name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm test
    
    - name: Install latest npm
      run: npm install -g npm@latest

    - name: Snyk Security Check
      run: npx snyk test --org= anna.bawor 
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Send Failure Email
   
    # if': failure()
    #uses: dawidd6/action-send-mail@v2
    #with:
    #server_address: smtp.gmail.com
    #server_port: 465
    #username: ${{secrets.EMAIL_USERNAME}}
    #password: ${{secrets.EMAIL_PASSWORD}}
    #subject: Snyk Security Issue Detected
    #body: Security issues found in the project. Please check the GitHub Actions log for more details.
    #to: anna.bawor@docc.techstarter.de
    #from: GitHub Actions 




